Repository valeriupredoi/bgcval2, pull requests merged in 2023-02, with the labels that each got.

#75 Nowmaps
  .github/workflows/run-tests-push.yml
  .github/workflows/run-tests.yml
  README.md
  bgcval2/Paths/paths.py
  bgcval2/UKESMpython.py
  bgcval2/_runtime_config.py
  bgcval2/analysis_p2p.py
  bgcval2/analysis_timeseries.py
  bgcval2/bgcvaltools/makeMask.py
  bgcval2/bgcvaltools/pftnames.py
  bgcval2/default-bgcval2-config.yml
  bgcval2/functions/globalVolMean.py
  bgcval2/functions/standard_functions.py
  bgcval2/netcdf_manipulation/convertToOneDNC.py
  bgcval2/netcdf_manipulation/mergeNC.py
  bgcval2/p2p/makeTargets.py
  bgcval2/p2p/matchDataAndModel.py
  bgcval2/p2p/p2pPlots.py
  bgcval2/p2p/slicesDict.py
  bgcval2/p2p/summaryTargets.py
  bgcval2/p2p/testsuite_p2p.py
  bgcval2/timeseries/timeseriesAnalysis.py
  bgcval2/timeseries/timeseriesPlots.py
  bgcval2/timeseries/timeseriesTools.py
  environment.yml
  input_yml/integration_testing.yml
  key_files/amm7_globalmeanph.yml
  key_files/amm7_globalmeantemperature.yml
  key_files/amm7_o3c.yml
  key_files/amm7_sss.yml
  key_files/amm7_sst.yml
  key_files/amm7_talk.yml
  key_files/oxygen.yml
  key_files/temperature_integration_test.yml
  key_lists/bgc_p2p.yml
  key_lists/integration_test.yml
  key_lists/nowmaps.yml
  key_lists/physics_p2p.yml
  setup.cfg
  setup.py
  tests/integration/test_analysis_compare_end-end.py
  tests/integration/test_analysis_timeseries_end-end.py
  tests/integration/test_command_line.py
Labels: diagnostics

#84 Move `UKESMpython.py` module in `bgcvaltools`
  .gitignore
  bgcval2/Paths/paths_template.py
  bgcval2/_runtime_config.py
  bgcval2/analysis_compare.py
  bgcval2/analysis_level3_amoc.py
  bgcval2/analysis_level3_dms.py
  bgcval2/analysis_level3_omz.py
  bgcval2/analysis_level3_sameYear.py
  bgcval2/analysis_p2p.py
  bgcval2/analysis_timeseries.py
  bgcval2/bgcval.py
  bgcval2/bgcval2_make_report.py
  bgcval2/bgcvaltools/bv2tools.py
  bgcval2/bgcvaltools/communitystructure.py
  bgcval2/bgcvaltools/linkTwoJobs.py
  bgcval2/bgcvaltools/makeEORCAmasks.py
  bgcval2/bgcvaltools/makeMask.py
  bgcval2/bgcvaltools/mergeMonthlyFiles.py
  bgcval2/bgcvaltools/pftnames.py
  bgcval2/bgcvaltools/prepareERSEMyear.py
  bgcval2/bgcvaltools/prepareMEDUSAyear.py
  bgcval2/bgcvaltools/regionMapLegend.py
  bgcval2/check_basic_run.sh
  bgcval2/functions/circulation.py
  bgcval2/index.rst
  bgcval2/p2p/makePatternStatsPlots.py
  bgcval2/p2p/makeTargets.py
  bgcval2/p2p/matchDataAndModel.py
  bgcval2/p2p/p2pPlots.py
  bgcval2/p2p/patternAnalyses.py
  bgcval2/p2p/shelveToDictionary.py
  bgcval2/p2p/slicesDict.py
  bgcval2/p2p/summaryTargets.py
  bgcval2/p2p/testsuite_p2p.py
  bgcval2/timeseries/extentMaps.py
  bgcval2/timeseries/extentProfiles.py
  bgcval2/timeseries/profileAnalysis.py
  bgcval2/timeseries/timeseriesAnalysis.py
  bgcval2/timeseries/timeseriesPlots.py
  bgcval2/timeseries/timeseriesTools.py
  input_yml/integration_testing.yml
  key_files/dic.yml
  key_lists/debug.yml
Labels: enhancement

#77 Improve installation docs
  README.md
Labels: documentation

#87 Terrafirma debugging
  bgcval2/analysis_compare.py
  bgcval2/bgcvaltools/bv2tools.py
  bgcval2/functions/circulation.py
  bgcval2/functions/globalVolMean.py
  bgcval2/functions/standard_functions.py
  bgcval2/p2p/makePatternStatsPlots.py
  bgcval2/timeseries/timeseriesTools.py
  input_yml/TerraFIRMA_overshoot_pi.yml
  key_lists/debug.yml
  tests/integration/test_analysis_timeseries.py
Labels: bug

#80 Addition of carbonate chemistry files
  bgcval2/bgcvaltools/pftnames.py
  bgcval2/functions/BenCa.py
  bgcval2/functions/InvtAlk.py
  input_yml/ocean_alkalisation.yml
  input_yml/ukesm_oae_rate.yml
  key_files/caco3_production.yml
  key_files/seafloor_omega_aragonite.yml
  key_files/seafloor_omega_calcite.yml
  key_files/surface_omega_aragonite.yml
  key_files/surface_omega_calcite.yml
  key_files/totalbenca.yml
  key_files/totalinvtalk.yml
  key_lists/alkalinity_norivalk.yml
Labels: enhancement, diagnostics

#89 Pin nctoolkit to use linux64 build rather than noarch
  environment.yml
  setup.py
Labels: installation
