Repository valeriupredoi/bgcval2, pull requests merged in 2023-01, with the labels that each got.

#70 Fix auto download permissions
  bgcval2/download_from_mass.py
Labels: enhancement

#74 Support for Python=3.10
  .github/workflows/build-and-deploy-on-pypi.yml
  .github/workflows/run-tests-push.yml
  .github/workflows/run-tests.yml
  bgcval2/timeseries/extentMaps.py
  bgcval2/timeseries/extentProfiles.py
  bgcval2/timeseries/timeseriesPlots.py
  environment.yml
  setup.py
  tests/integration/test_basemap.py
Labels: installation

#78 minor typo in PyPI package builder Github Actions
  .github/workflows/build-and-deploy-on-pypi.yml
Labels: bug
